sudo: required
dist: trusty

language: python
python:
- '2.7'

env:
  matrix:
  - ANSIBLE_REF='ansible==2.5.0' BASE_IMAGE=ubuntu:xenial
  - ANSIBLE_REF='ansible==2.5.0' BASE_IMAGE=debian:stretch
  - ANSIBLE_REF='ansible<2.5' BASE_IMAGE=ubuntu:xenial
  - ANSIBLE_REF='ansible<2.5' BASE_IMAGE=debian:stretch

install:
  - travis_retry pip install --upgrade pip setuptools wheel
  - travis_retry pip install "${ANSIBLE_REF}" molecule docker-py

script:
  - molecule test --driver-name docker

