---
- name: Include OS-specific variables for Fedora or FreeBSD.
  include_vars: "{{ ansible_facts.distribution }}.yml"
  when: ansible_facts.distribution == 'FreeBSD' or ansible_facts.distribution == 'Fedora'

- name: Include OS-specific variables for Amazon.
  include_vars: "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version}}.yml"
  when: ansible_facts.distribution == 'Amazon'

- name: Include version-specific variables for CentOS/RHEL.
  include_vars: "RedHat-{{ ansible_facts.distribution_version.split('.')[0] }}.yml"
  when: >-
    ansible_facts.distribution in [
      'CentOS',
      'Red Hat Enterprise Linux',
      'RedHat',
      'OracleLinux',
      'Rocky',
      'AlmaLinux'
    ]

- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version.split('.')[0] }}.yml"
  when: ansible_facts.distribution == 'Ubuntu'

- name: Include version-specific variables for Debian.
  include_vars: "{{ ansible_facts.distribution | title }}-{{ ansible_facts.distribution_version.split('.')[0] }}.yml"
  when: ansible_facts.os_family == 'Debian'

- name: Define java_packages.
  set_fact:
    java_packages: "{{ __java_packages | list }}"
  when: java_packages is not defined

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_facts.os_family == 'RedHat'

- include_tasks: setup-Amazon.yml
  when: ansible_facts.distribution == 'Amazon'

- include_tasks: setup-Debian.yml
  when: ansible_facts.os_family == 'Debian'

- include_tasks: setup-FreeBSD.yml
  when: ansible_facts.os_family == 'FreeBSD'

# Environment setup.
- name: Set JAVA_HOME if configured.
  template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
  when: java_home is defined and java_home != ""
